spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0.23:///test?useUnicode=true&characterEncoding=UTF-8&TC_INITSCRIPT=init.sql
    username: test
    password: test
